### ISSUE TITLE
Chưa có file ctl-10-ceilometer.sh

### ISSUE THREAD

**Issue by uncelvel** [vietstacker/openstack-liberty-multinode#8]
Cài đặt Ceilomter

bash ctl-10-ceilometer.sh

Chưa có file này bác Công ơi.

**Comment by congto** [comment]
@uncelvel  có rồi mà, check lại gúp mình với !

https://github.com/vietstacker/openstack-liberty-multinode/blob/master/LIBERTY-U14.04-OVS/ctl-10-ceilometer.sh

**Comment by uncelvel** [comment]
Dạ vâng ạ, em thấy rồi ạ. :D
